/**
 * `llms.txt` generation.
 *
 * Markdown is how AI assistants read the web; a site published only as HTML is
 * effectively invisible to them. These two files are the plain-text surface of
 * the documentation, following the llms.txt convention.
 */

/**
 * Docs sites suffix every page title with the site name (`Guide · Acme Docs`).
 * Every entry in `llms.txt` would otherwise carry that noise. Stripping is done
 * here rather than by the caller so the invariant holds no matter who builds
 * the page list — the function is idempotent, so a pre-stripped list is fine.
 * @param {Array<{title: string}>} pages
 * @returns {Array<object>}
 */
export function stripCommonTitleSuffix(pages) {
  if (pages.length < 3) {
    return pages;
  }
  const separator = /\s*[·|]\s*|\s+[–—-]\s+/;
  const counters = new Map();

  for (const page of pages) {
    const parts = String(page.title).split(separator);
    if (parts.length < 2) {
      continue;
    }
    const suffix = parts[parts.length - 1].trim();
    if (suffix === '' || suffix.length > 40) {
      continue;
    }
    counters.set(suffix, (counters.get(suffix) || 0) + 1);
  }

  let best = '';
  let bestCount = 0;
  for (const [suffix, count] of counters) {
    if (count > bestCount) {
      best = suffix;
      bestCount = count;
    }
  }
  if (best === '' || bestCount < Math.ceil(pages.length * 0.6)) {
    return pages;
  }

  return pages.map((page) => {
    const parts = String(page.title).split(separator);
    if (parts.length >= 2 && parts[parts.length - 1].trim() === best) {
      const trimmed = parts.slice(0, -1).join(' · ').trim();
      return { ...page, title: trimmed === '' ? page.title : trimmed };
    }
    return page;
  });
}

const ACRONYMS = new Set([
  'api', 'cli', 'sdk', 'mcp', 'ui', 'ux', 'http', 'https', 'json', 'sql', 'ai',
  'ml', 'css', 'html', 'js', 'ts', 'gui', 'dns', 'tls', 'ssl', 'jwt', 'url',
  'faq', 'sso', 'iam', 'gpu', 'cpu', 'llm',
]);

/**
 * @param {string} segment
 * @returns {string}
 */
function titleize(segment) {
  const words = segment.replace(/[-_]+/g, ' ').trim();
  return words
    .split(' ')
    .map((word) =>
      ACRONYMS.has(word.toLowerCase())
        ? word.toUpperCase()
        : word.charAt(0).toUpperCase() + word.slice(1),
    )
    .join(' ');
}

/**
 * @param {{name: string, summary: string, detail?: string, source: string}} meta
 * @param {Array<{path: string, url: string, title: string, description: string}>} pages
 * @returns {string}
 */
export function renderLlmsTxt(meta, pages) {
  const lines = [`# ${meta.name}`, '', `> ${meta.summary}`, ''];
  if (meta.detail) {
    lines.push(meta.detail, '');
  }

  pages = stripCommonTitleSuffix(pages);

  const groups = new Map();
  for (const page of pages) {
    const segments = page.path.split('/');
    const group = segments.length > 1 ? segments[0] : '';
    if (!groups.has(group)) {
      groups.set(group, []);
    }
    groups.get(group).push(page);
  }

  const orderedGroups = [...groups.keys()].sort((a, b) => {
    if (a === '') {
      return -1;
    }
    if (b === '') {
      return 1;
    }
    return a.localeCompare(b);
  });

  for (const group of orderedGroups) {
    lines.push(`## ${group === '' ? 'Overview' : titleize(group)}`, '');
    const list = groups.get(group).slice().sort((a, b) => a.path.localeCompare(b.path));
    for (const page of list) {
      const description = page.description ? `: ${page.description}` : '';
      lines.push(`- [${page.title}](${page.url})${description}`);
    }
    lines.push('');
  }

  lines.push(
    '## About this file',
    '',
    `Generated by hanmcp from ${meta.source}. Companion files: \`llms-full.txt\` (every page inlined) and \`server.mjs\` (an MCP server exposing the same content as agent tools).`,
    '',
  );

  return lines.join('\n');
}

/**
 * @param {{name: string, summary: string, source: string}} meta
 * @param {Array<{url: string, title: string, markdown: string}>} pages
 * @returns {string}
 */
export function renderLlmsFullTxt(meta, pages) {
  const parts = [`# ${meta.name}`, '', `> ${meta.summary}`, '', `Source: ${meta.source}`, ''];
  for (const page of pages) {
    parts.push('---', '', `## ${page.title}`, '', page.url, '', page.markdown, '');
  }
  return parts.join('\n');
}
